### ISSUE TITLE
Question about example 2

### ISSUE THREAD

**Issue by AlexandreRoy5** [kurosawa4434/checkio-mission-stacking-cubes#3]
Hello, 

This checkio problem is great and I had a great time building a solution to it. Thanks for it :). However, there is a point I could not understand well when reading the description. This is related to example 2 :

> stacking_cubes([(0, 0, 2), (1, 1, 2), (1, 2, 1), (2, 2, 2)]) == 6. 

When solving it manually, I thought the height should be 7. So I interpreted the instruction :

> if at least 1x1 faces of the cubes touch, they will be stacked.

as "the cubes must have the same size to be stacked". But when checking my solution, the first extra test failed because it stacks two cubes of different size... 

So I am now wondering if I missed something or if the answer to the second test should be 7 ?

Thanks and good luck

BWolfS

**Comment by kurosawa4434** [comment]
Hi BWolfS :-)

>as "the cubes must have the same size to be stacked"

You can stacking cubes of different size.

And by the following condition, The answer is 6:

>but the X and Y coordinates of the cubes can't be changed;

If you still have problems, post your solution here.

**Comment by AlexandreRoy5** [comment]
Hello, 

Ok, now I see why my solution failed :). Thanks, I'll update it soon !!
